/*
 * Q2 - Producer Consumer Sensor Simulation
 *
 * This program simulates an external sensor using two threads.
 * The producer generates random sensor bytes every simulated second
 * and stores them in a shared buffer.
 * The consumer checks the buffer every 10 simulated seconds.
 * If at least 50 bytes are available, it prints the latest
 * 50 bytes in hexadecimal format.
 *
 * Assumption:
 * 1 simulated second = 200 ms to reduce execution time.
 */

#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <unistd.h>
#include <time.h>

// Maximum size of the shared buffer
#define BUFFER_SIZE 500

// Minimum bytes required before printing
#define LIMIT 50

// Total simulation time
#define SIM_TIME 30

// 200 ms represents 1 simulated second
#define TICK 200

// Shared buffer to store generated sensor bytes
unsigned char dataBuffer[BUFFER_SIZE];

// Number of valid bytes currently stored
int dataCount = 0;

// Mutex to protect shared buffer from simultaneous access
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;

/*
 * Producer Thread
 * Generates random sensor data every simulated second
 * and stores it in the shared buffer.
 */
void *producer(void *arg)
{
    for (int sec = 1; sec <= SIM_TIME; sec++)
    {
        // Wait for one simulated second
        usleep(TICK * 1000);

        // Generate 0 to 5 random bytes
        int bytes = rand() % 6;

        // Lock the buffer before writing
        pthread_mutex_lock(&mutex);

        // Store generated bytes into the shared buffer
        for (int i = 0; i < bytes && dataCount < BUFFER_SIZE; i++)
        {
            dataBuffer[dataCount++] = rand() % 256;
        }

        // Display producer activity
        printf("[Producer] t=%2d s | Added %d bytes | Total = %d\n",
               sec, bytes, dataCount);

        // Release the buffer
        pthread_mutex_unlock(&mutex);
    }

    return NULL;
}

/*
 * Consumer Thread
 * Checks the buffer every 10 simulated seconds.
 * If at least 50 bytes are available,
 * it prints the latest 50 bytes.
 */
void *consumer(void *arg)
{
    for (int sec = 10; sec <= SIM_TIME; sec += 10)
    {
        // Wait for 10 simulated seconds
        usleep(TICK * 1000 * 10);

        // Lock the buffer before reading
        pthread_mutex_lock(&mutex);

        printf("\n[Consumer] t=%2d s\n", sec);

        // Check whether enough data is available
        if (dataCount >= LIMIT)
        {
            printf("Latest %d bytes:\n", LIMIT);

            // Find the starting position of the latest 50 bytes
            int start = dataCount - LIMIT;

            // Print bytes in hexadecimal format
            for (int i = start; i < dataCount; i++)
            {
                printf("%02X ", dataBuffer[i]);

                // Print 16 bytes per line for better readability
                if ((i - start + 1) % 16 == 0)
                    printf("\n");
            }

            printf("\n");

            // Remove printed bytes logically
            dataCount = start;

            printf("Remaining bytes = %d\n\n", dataCount);
        }
        else
        {
            // Buffer does not have enough data
            printf("Only %d bytes available. Nothing printed.\n\n", dataCount);
        }

        // Release the buffer
        pthread_mutex_unlock(&mutex);
    }

    return NULL;
}

/*
 * Main Function
 * Creates producer and consumer threads
 * and waits until both finish execution.
 */
int main()
{
    // Initialize random number generator
    srand(time(NULL));

    pthread_t producerThread;
    pthread_t consumerThread;

    // Create producer and consumer threads
    pthread_create(&producerThread, NULL, producer, NULL);
    pthread_create(&consumerThread, NULL, consumer, NULL);

    // Wait for both threads to complete
    pthread_join(producerThread, NULL);
    pthread_join(consumerThread, NULL);

    // Destroy the mutex before exiting
    pthread_mutex_destroy(&mutex);

    return 0;
}